import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../../core/config/supabase_client.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/widgets/error_widget.dart';
import '../../../core/widgets/loading_widget.dart';
import '../../inventory/providers/inventory_provider.dart';
import '../../inventory/data/models/supplier_model.dart';
import '../../vendors/screens/vendor_analytics_dashboard.dart';
import '../data/models/report_models.dart';
import '../providers/report_provider.dart';

class ReportsScreen extends ConsumerStatefulWidget {
  final String? projectId;

  const ReportsScreen({super.key, this.projectId});

  @override
  ConsumerState<ReportsScreen> createState() => _ReportsScreenState();
}

class _ReportsScreenState extends ConsumerState<ReportsScreen> {
  bool _isExporting = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      ref
          .read(reportProvider.notifier)
          .loadReports(projectId: widget.projectId);
    });
  }

  Future<void> _exportPdf(ReportState state) async {
    if (_isExporting) return;
    setState(() => _isExporting = true);
    try {
      final doc = pw.Document();
      final stats = state.stats;
      final generatedAt = DateTime.now();

      doc.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context ctx) => [
            // Header
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Project Insights Report',
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.Text(
                  '${generatedAt.day}/${generatedAt.month}/${generatedAt.year}',
                  style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey600),
                ),
              ],
            ),
            if (widget.projectId != null)
              pw.Text(
                'Project ID: ${widget.projectId}',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
              ),
            pw.SizedBox(height: 16),
            pw.Divider(),
            pw.SizedBox(height: 12),

            // Financial Summary
            pw.Text(
              'Financial Summary',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 8),
            _pdfRow('Total Expenses', '₹${stats.totalExpenses.toStringAsFixed(2)}'),
            _pdfRow('Labour Cost', '₹${stats.laborCost.toStringAsFixed(2)}'),
            _pdfRow('Material Cost', '₹${stats.materialCost.toStringAsFixed(2)}'),
            _pdfRow('Machinery Cost', '₹${stats.machineryCost.toStringAsFixed(2)}'),
            _pdfRow('Other Cost', '₹${stats.otherCost.toStringAsFixed(2)}'),
            pw.SizedBox(height: 16),

            // Cost Breakdown Table
            if (stats.chartData.isNotEmpty) ...[
              pw.Text(
                'Monthly Breakdown',
                style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 8),
              pw.TableHelper.fromTextArray(
                headers: ['Period', 'Amount (₹)'],
                data: stats.chartData
                    .map((d) => [d.label, d.value.toStringAsFixed(2)])
                    .toList(),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                cellAlignment: pw.Alignment.centerLeft,
                headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey100),
              ),
              pw.SizedBox(height: 16),
            ],

            // Footer
            pw.Divider(),
            pw.SizedBox(height: 8),
            pw.Text(
              'Generated by Clivi Management App · ${generatedAt.toIso8601String()}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
            ),
          ],
        ),
      );

      await Printing.layoutPdf(
        onLayout: (_) async => doc.save(),
        name: 'report_${widget.projectId ?? "all"}_${generatedAt.millisecondsSinceEpoch}.pdf',
      );
    } catch (e) {
      logger.e('PDF export failed: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Export failed: $e'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isExporting = false);
    }
  }

  pw.Widget _pdfRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 11)),
          pw.Text(value,
              style: pw.TextStyle(
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
              )),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(reportProvider);
    final notifier = ref.read(reportProvider.notifier);
    final suppliersAsync = ref.watch(suppliersProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Insights'),
        actions: [
          if (_isExporting)
            const Padding(
              padding: EdgeInsets.symmetric(horizontal: 16),
              child: SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(strokeWidth: 2),
              ),
            )
          else
            IconButton(
              icon: const Icon(Icons.download),
              tooltip: 'Export PDF',
              onPressed: () => _exportPdf(state),
            ),
        ],
      ),
      body: RefreshIndicator(
        onRefresh: () => notifier.refresh(projectId: widget.projectId),
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              suppliersAsync.when(
                data: (suppliers) => _VendorFilter(
                  suppliers: suppliers,
                  selectedVendorId: state.selectedVendorId,
                  onChanged: (vendorId) =>
                      notifier.setVendor(vendorId, projectId: widget.projectId),
                ),
                loading: () => const Align(
                  alignment: Alignment.centerLeft,
                  child: SizedBox(
                    height: 16,
                    width: 16,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  ),
                ),
                error: (error, stack) => const SizedBox.shrink(),
              ),
              const SizedBox(height: 12),

              // Time Period Tabs
              _TimeFilterTabs(
                selectedPeriod: state.selectedPeriod,
                onSelect: (period) =>
                    notifier.setPeriod(period, projectId: widget.projectId),
              ),
              const SizedBox(height: 24),

              if (state.isLoading && state.stats == FinancialStats.empty)
                const LoadingWidget(message: 'Loading insights...')
              else if (state.error != null &&
                  state.stats == FinancialStats.empty)
                AppErrorWidget(
                  message: state.error!,
                  onRetry: () => notifier.refresh(),
                )
              else ...[
                // Financial Health Card (Line Chart)
                _FinancialHealthCard(stats: state.stats),
                const SizedBox(height: 24),

                // Resource Split Card (Donut Chart)
                _ResourceSplitCard(stats: state.stats),
                const SizedBox(height: 24),

                // Vendor Analytics Section (Admin Only)
                if (widget.projectId == null) ...[
                  _VendorAnalyticsSection(),
                  const SizedBox(height: 24),
                ],

                // Operations mini-reports
                _OperationsReports(
                  materialRows: state.materialVendors,
                  machineryRows: state.machineryProjects,
                  labourRows: state.labourProjects,
                  isLoading: state.isLoading,
                ),
                const SizedBox(height: 24),

                // Insights Tip
                if (state.stats.growthPercentage != 0)
                  _InsightTip(growth: state.stats.growthPercentage),

                // Extra padding for scroll
                const SizedBox(height: 40),
              ],
            ],
          ),
        ),
      ),
    );
  }
}

class _TimeFilterTabs extends StatelessWidget {
  final TimePeriod selectedPeriod;
  final Function(TimePeriod) onSelect;

  const _TimeFilterTabs({required this.selectedPeriod, required this.onSelect});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(4),
      decoration: BoxDecoration(
        color: Colors.grey[200],
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        children: TimePeriod.values.map((period) {
          final isSelected = selectedPeriod == period;
          return Expanded(
            child: GestureDetector(
              onTap: () => onSelect(period),
              child: Container(
                padding: const EdgeInsets.symmetric(vertical: 10),
                decoration: BoxDecoration(
                  color: isSelected ? Colors.white : Colors.transparent,
                  borderRadius: BorderRadius.circular(8),
                  boxShadow: isSelected
                      ? [
                          BoxShadow(
                            color: Colors.black.withValues(alpha: 0.1),
                            blurRadius: 4,
                            offset: const Offset(0, 2),
                          ),
                        ]
                      : null,
                ),
                alignment: Alignment.center,
                child: Text(
                  period.label,
                  style: TextStyle(
                    fontWeight: isSelected ? FontWeight.bold : FontWeight.w500,
                    color: isSelected
                        ? AppColors.primary
                        : AppColors.textSecondary,
                    fontSize: 13,
                  ),
                ),
              ),
            ),
          );
        }).toList(),
      ),
    );
  }
}

class _FinancialHealthCard extends StatelessWidget {
  final FinancialStats stats;

  const _FinancialHealthCard({required this.stats});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 20,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Financial Health',
            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 16),
          Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'TOTAL EXPENSES',
                    style: TextStyle(
                      fontSize: 11,
                      color: AppColors.textSecondary,
                      fontWeight: FontWeight.w600,
                      letterSpacing: 0.5,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Row(
                    children: [
                      Text(
                        '₹ ${stats.totalExpenses >= 100000 ? '${(stats.totalExpenses / 100000).toStringAsFixed(1)} L' : stats.totalExpenses.toStringAsFixed(0)}',
                        style: const TextStyle(
                          fontSize: 24,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(width: 8),
                      Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 6,
                          vertical: 2,
                        ),
                        decoration: BoxDecoration(
                          color:
                              (stats.growthPercentage >= 0
                                      ? AppColors.success
                                      : AppColors.error)
                                  .withValues(alpha: 0.1),
                          borderRadius: BorderRadius.circular(4),
                        ),
                        child: Text(
                          '${stats.growthPercentage >= 0 ? '+' : ''}${stats.growthPercentage}%',
                          style: TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.bold,
                            color: stats.growthPercentage >= 0
                                ? AppColors.success
                                : AppColors.error,
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
              const Spacer(),
              Icon(
                Icons.pie_chart_outline,
                color: AppColors.primary.withValues(alpha: 0.2),
                size: 32,
              ),
            ],
          ),
          const SizedBox(height: 24),
          SizedBox(
            height: 180,
            child: LineChart(
              LineChartData(
                gridData: FlGridData(show: false),
                titlesData: FlTitlesData(
                  bottomTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: true,
                      getTitlesWidget: (value, meta) {
                        if (stats.chartData.isEmpty) {
                          return const SizedBox.shrink();
                        }
                        final index = value.toInt();
                        if (index < 0 || index >= stats.chartData.length) {
                          return const SizedBox.shrink();
                        }
                        // Show every 2nd or 3rd label if too many
                        if (stats.chartData.length > 6 && index % 2 != 0) {
                          return const SizedBox.shrink();
                        }
                        return Padding(
                          padding: const EdgeInsets.only(top: 8),
                          child: Text(
                            stats.chartData[index].label,
                            style: const TextStyle(
                              color: AppColors.textSecondary,
                              fontSize: 10,
                            ),
                          ),
                        );
                      },
                      reservedSize: 22,
                    ),
                  ),
                  leftTitles: AxisTitles(
                    sideTitles: SideTitles(showTitles: false),
                  ),
                  topTitles: AxisTitles(
                    sideTitles: SideTitles(showTitles: false),
                  ),
                  rightTitles: AxisTitles(
                    sideTitles: SideTitles(showTitles: false),
                  ),
                ),
                borderData: FlBorderData(show: false),
                lineBarsData: [
                  LineChartBarData(
                    spots: stats.chartData.asMap().entries.map((e) {
                      return FlSpot(e.key.toDouble(), e.value.value);
                    }).toList(),
                    isCurved: true,
                    color: AppColors.primary,
                    barWidth: 3,
                    isStrokeCapRound: true,
                    dotData: FlDotData(show: false),
                    belowBarData: BarAreaData(
                      show: true,
                      color: AppColors.primary.withValues(alpha: 0.1),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _ResourceSplitCard extends StatelessWidget {
  final FinancialStats stats;

  const _ResourceSplitCard({required this.stats});

  @override
  Widget build(BuildContext context) {
    // Calculate total for percentage
    final total =
        stats.laborCost +
        stats.materialCost +
        stats.machineryCost +
        stats.otherCost;

    // Avoid division by zero
    final safeTotal = total > 0 ? total : 1.0;

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 20,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Resource Split',
            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 24),
          Row(
            children: [
              // Donut Chart
              SizedBox(
                height: 120,
                width: 120,
                child: PieChart(
                  PieChartData(
                    sectionsSpace: 0,
                    centerSpaceRadius: 40,
                    sections: [
                      PieChartSectionData(
                        color: AppColors.warning,
                        value: stats.laborCost,
                        title: '',
                        radius: 12,
                      ),
                      PieChartSectionData(
                        color: AppColors.success,
                        value: stats.materialCost,
                        title: '',
                        radius: 12,
                      ),
                      PieChartSectionData(
                        color: AppColors.primary,
                        value: stats.machineryCost,
                        title: '',
                        radius: 12,
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(width: 24),
              // Legend
              Expanded(
                child: Column(
                  children: [
                    _LegendItem(
                      color: AppColors.warning,
                      label: 'Labor',
                      percentage: (stats.laborCost / safeTotal * 100).round(),
                    ),
                    const SizedBox(height: 12),
                    _LegendItem(
                      color: AppColors.success,
                      label: 'Material',
                      percentage: (stats.materialCost / safeTotal * 100)
                          .round(),
                    ),
                    const SizedBox(height: 12),
                    _LegendItem(
                      color: AppColors.primary,
                      label: 'Machinery',
                      percentage: (stats.machineryCost / safeTotal * 100)
                          .round(),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _LegendItem extends StatelessWidget {
  final Color color;
  final String label;
  final int percentage;

  const _LegendItem({
    required this.color,
    required this.label,
    required this.percentage,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Container(
          width: 8,
          height: 8,
          decoration: BoxDecoration(color: color, shape: BoxShape.circle),
        ),
        const SizedBox(width: 8),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                label,
                style: const TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 2),
              ClipRRect(
                borderRadius: BorderRadius.circular(2),
                child: LinearProgressIndicator(
                  value: percentage / 100,
                  backgroundColor: AppColors.border.withValues(alpha: 0.3),
                  valueColor: AlwaysStoppedAnimation<Color>(color),
                  minHeight: 4,
                ),
              ),
            ],
          ),
        ),
        const SizedBox(width: 12),
        Text(
          '$percentage%',
          style: const TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.bold,
            color: AppColors.textSecondary,
          ),
        ),
      ],
    );
  }
}

class _InsightTip extends StatelessWidget {
  final double growth;

  const _InsightTip({required this.growth});

  @override
  Widget build(BuildContext context) {
    if (growth == 0) return const SizedBox.shrink();

    final isPositive = growth > 0;
    // For expenses, positive growth might actually be bad (spending more),
    // but typically "Running faster" implies efficiency.
    // For now we'll stick to a simple interpretation:
    // "Projects running X% [higher/lower] than last period"

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.secondary,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.white.withValues(alpha: 0.2),
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.lightbulb_outline,
              color: Colors.white,
              size: 20,
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Text(
              'Your projects are running ${growth.abs()}% ${isPositive ? 'higher' : 'lower'} than last period targets.',
              style: const TextStyle(
                color: Colors.white,
                fontSize: 13,
                height: 1.4,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _VendorAnalyticsSection extends StatelessWidget {
  const _VendorAnalyticsSection();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [Colors.purple[700]!, Colors.purple[500]!],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.purple.withValues(alpha: 0.3),
            blurRadius: 20,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => const VendorAnalyticsDashboard(),
              ),
            );
          },
          borderRadius: BorderRadius.circular(20),
          child: Padding(
            padding: const EdgeInsets.all(4),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.white.withValues(alpha: 0.2),
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: const Icon(Icons.store, color: Colors.white, size: 32),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Vendor Analytics',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        'Payment tracking • Stock history • Credit limits',
                        style: TextStyle(
                          color: Colors.white.withValues(alpha: 0.9),
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                ),
                const Icon(
                  Icons.arrow_forward_ios,
                  color: Colors.white,
                  size: 18,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _VendorFilter extends StatelessWidget {
  final List<SupplierModel> suppliers;
  final String? selectedVendorId;
  final ValueChanged<String?> onChanged;

  const _VendorFilter({
    required this.suppliers,
    required this.selectedVendorId,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField<String?>(
      initialValue: selectedVendorId,
      decoration: InputDecoration(
        labelText: 'Vendor',
        isDense: true,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 12,
          vertical: 10,
        ),
      ),
      items: [
        const DropdownMenuItem<String?>(
          value: null,
          child: Text('All vendors'),
        ),
        ...suppliers.map(
          (s) => DropdownMenuItem<String?>(value: s.id, child: Text(s.name)),
        ),
      ],
      onChanged: onChanged,
    );
  }
}

class _OperationsReports extends StatelessWidget {
  final List<MaterialVendorReportRow> materialRows;
  final List<MachineryProjectReportRow> machineryRows;
  final List<LabourProjectReportRow> labourRows;
  final bool isLoading;

  const _OperationsReports({
    required this.materialRows,
    required this.machineryRows,
    required this.labourRows,
    required this.isLoading,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Operations Reports',
          style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
        ),
        const SizedBox(height: 12),
        _ReportCard(
          title: 'Material by Vendor & Project',
          isLoading: isLoading,
          child: materialRows.isEmpty
              ? const _EmptyRow(message: 'No material receipts yet')
              : Column(
                  children: materialRows.take(6).map((row) {
                    return _TwoLineTile(
                      title: '${row.materialName} • ${row.vendorName}',
                      subtitle:
                          '${row.projectName} • ${row.totalReceived.toStringAsFixed(1)} ${row.unit}',
                      trailing: row.lastReceivedAt != null
                          ? _dateLabel(row.lastReceivedAt!)
                          : '',
                    );
                  }).toList(),
                ),
        ),
        const SizedBox(height: 12),
        _ReportCard(
          title: 'Machinery by Project',
          isLoading: isLoading,
          child: machineryRows.isEmpty
              ? const _EmptyRow(message: 'No machinery logs yet')
              : Column(
                  children: machineryRows.take(6).map((row) {
                    return _TwoLineTile(
                      title:
                          '${row.machineryName}${row.machineryType.isNotEmpty ? ' (${row.machineryType})' : ''}',
                      subtitle:
                          '${row.projectName} • ${row.totalHours.toStringAsFixed(1)} hrs',
                      trailing: row.lastWorkedAt != null
                          ? _dateLabel(row.lastWorkedAt!)
                          : '',
                    );
                  }).toList(),
                ),
        ),
        const SizedBox(height: 12),
        _ReportCard(
          title: 'Labour by Project',
          isLoading: isLoading,
          child: labourRows.isEmpty
              ? const _EmptyRow(message: 'No active labour found')
              : Column(
                  children: labourRows.take(6).map((row) {
                    final wage = row.dailyWage > 0
                        ? '₹${row.dailyWage.toStringAsFixed(0)} /day'
                        : '';
                    return _TwoLineTile(
                      title:
                          '${row.labourName}${row.skillType.isNotEmpty ? ' • ${row.skillType}' : ''}',
                      subtitle:
                          '${row.projectName}${wage.isNotEmpty ? ' • $wage' : ''}',
                    );
                  }).toList(),
                ),
        ),
      ],
    );
  }

  String _dateLabel(DateTime date) {
    return '${date.day}/${date.month}/${date.year}';
  }
}

class _ReportCard extends StatelessWidget {
  final String title;
  final Widget child;
  final bool isLoading;

  const _ReportCard({
    required this.title,
    required this.child,
    required this.isLoading,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 16,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                title,
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w700,
                ),
              ),
              if (isLoading)
                const SizedBox(
                  height: 14,
                  width: 14,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
            ],
          ),
          const SizedBox(height: 12),
          child,
        ],
      ),
    );
  }
}

class _TwoLineTile extends StatelessWidget {
  final String title;
  final String subtitle;
  final String? trailing;

  const _TwoLineTile({
    required this.title,
    required this.subtitle,
    this.trailing,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: const TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  subtitle,
                  style: TextStyle(
                    fontSize: 12,
                    color: AppColors.textSecondary,
                  ),
                ),
              ],
            ),
          ),
          if (trailing != null && trailing!.isNotEmpty)
            Text(
              trailing!,
              style: TextStyle(fontSize: 11, color: AppColors.textSecondary),
            ),
        ],
      ),
    );
  }
}

class _EmptyRow extends StatelessWidget {
  final String message;
  const _EmptyRow({required this.message});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Text(
        message,
        style: TextStyle(fontSize: 12, color: AppColors.textSecondary),
      ),
    );
  }
}
